"""D&D alignment question bank parsed from the Easydamus alignment test page.

Each option keeps the original JavaScript scoring bucket:
lx/nx/cx for law-neutral-chaos, xg/xn/xe for good-neutral-evil.
"""

VALID_MODES = ("full",)
MODE_QUESTION_TOTAL = {"full": 36}

FULL_QUESTIONS = [{'id': 1,
  'text': 'Family elders are expressing disapproval of you to the rest of the family.  Do you:',
  'options': [{'value': 1, 'text': 'Accept the criticism and change your ways?', 'bucket': 'xg', 'points': 2},
              {'value': 2, 'text': 'Seek a compromise with them?', 'bucket': 'xg', 'points': 1},
              {'value': 3,
               'text': 'Besmirch the reputation of those expressing disapproval as you ignore their scorn?',
               'bucket': 'xe',
               'points': 1},
              {'value': 4, 'text': 'Silence them any way you can?', 'bucket': 'xe', 'points': 2}],
  'axis': 'good_evil'},
 {'id': 2,
  'text': 'Would you give up a promising career to aid the family in time of need?',
  'options': [{'value': 1, 'text': 'In a heartbeat.', 'bucket': 'xg', 'points': 2},
              {'value': 2, 'text': 'Yes, with some reluctance.', 'bucket': 'xg', 'points': 1},
              {'value': 3,
               'text': "Only if I was certain I'd be able to return to my career soon.",
               'bucket': 'xn',
               'points': 1},
              {'value': 4, 'text': 'No.', 'bucket': 'xn', 'points': 2}],
  'axis': 'good_evil'},
 {'id': 3,
  'text': 'Would you betray a family member to advance your own career?',
  'options': [{'value': 1, 'text': 'Yes, without a twinge of guilt.', 'bucket': 'xe', 'points': 2},
              {'value': 2, 'text': 'Yes, if I could do it secretly.', 'bucket': 'xe', 'points': 1},
              {'value': 3, 'text': "I'd resist the temptation.", 'bucket': 'xn', 'points': 1},
              {'value': 4, 'text': 'I find the very idea abhorrent.', 'bucket': 'xn', 'points': 2}],
  'axis': 'good_evil'},
 {'id': 4,
  'text': 'Do you respect the leaders of your family?',
  'options': [{'value': 1, 'text': 'Their words guide my actions.', 'bucket': 'lx', 'points': 2},
              {'value': 2, 'text': "They're role models for me.", 'bucket': 'lx', 'points': 1},
              {'value': 3, 'text': "They're often out of touch with my life.", 'bucket': 'cx', 'points': 1},
              {'value': 4, 'text': "They're out of touch with reality.", 'bucket': 'cx', 'points': 2}],
  'axis': 'law_chaos'},
 {'id': 5,
  'text': 'If your family had arranged your marriage to someone loathsome, would you:',
  'options': [{'value': 1, 'text': 'Go through with it, proud to serve your family?', 'bucket': 'lx', 'points': 2},
              {'value': 2, 'text': 'Agree, hiding your reluctance?', 'bucket': 'lx', 'points': 1},
              {'value': 3, 'text': 'Subtly work against the union?', 'bucket': 'nx', 'points': 1},
              {'value': 4, 'text': 'Flee?', 'bucket': 'nx', 'points': 2}],
  'axis': 'law_chaos'},
 {'id': 6,
  'text': "You're estranged from a family member.  On his deathbed, he seeks reconciliation.  Do you:",
  'options': [{'value': 1, 'text': 'Speak to him, but hold your ground?', 'bucket': 'cx', 'points': 2},
              {'value': 2, 'text': 'Refuse to speak to him?', 'bucket': 'cx', 'points': 1},
              {'value': 3, 'text': 'Discuss your estrangement openly and without rancor?', 'bucket': 'nx', 'points': 1},
              {'value': 4,
               'text': 'Actively seek reconciliation, and heed his dying words?',
               'bucket': 'nx',
               'points': 2}],
  'axis': 'law_chaos'},
 {'id': 7,
  'text': "A powerful but corrupt judge offers you wealth if you'll testify against your friend.  Do you:",
  'options': [{'value': 1, 'text': 'Condemn your friend and take the money?', 'bucket': 'xe', 'points': 2},
              {'value': 2,
               'text': 'Take the money and testify, but try to keep your testimony ineffective?',
               'bucket': 'xe',
               'points': 1},
              {'value': 3, 'text': 'Refuse the offer and refuse to testify?', 'bucket': 'xg', 'points': 1},
              {'value': 4,
               'text': "Testify on your friend's behalf, no matter the consequences?",
               'bucket': 'xg',
               'points': 2}],
  'axis': 'good_evil'},
 {'id': 8,
  'text': 'Do you become close to friends, or hold most people at a safe distance?',
  'options': [{'value': 1, 'text': 'I have an abundance of close friends.', 'bucket': 'xg', 'points': 2},
              {'value': 2, 'text': 'I have some close friends.', 'bucket': 'xg', 'points': 1},
              {'value': 3, 'text': 'I have few close friends.', 'bucket': 'xn', 'points': 1},
              {'value': 4, 'text': 'I try to keep people at a distance.', 'bucket': 'xn', 'points': 2}],
  'axis': 'good_evil'},
 {'id': 9,
  'text': 'Have you ever betrayed a friend?',
  'options': [{'value': 1,
               'text': "I've done so more than once, and I sometimes get away with it.",
               'bucket': 'xe',
               'points': 2},
              {'value': 2, 'text': "I've done so once.", 'bucket': 'xe', 'points': 1},
              {'value': 3,
               'text': "I've been tempted to do so, but I've never gone through with it.",
               'bucket': 'xn',
               'points': 1},
              {'value': 4, 'text': "I'd never contemplate such a thing.", 'bucket': 'xn', 'points': 2}],
  'axis': 'good_evil'},
 {'id': 10,
  'text': 'How do you view lifelong commitment to a single romantic partner?',
  'options': [{'value': 1, 'text': 'I have or want such a romance.', 'bucket': 'lx', 'points': 2},
              {'value': 2, 'text': "Such a romance would be ideal--if it's achievable.", 'bucket': 'lx', 'points': 1},
              {'value': 3, 'text': "I worry I'd miss out on what others have to offer.", 'bucket': 'cx', 'points': 1},
              {'value': 4, 'text': 'Tie yourself to one person?  Huge mistake.', 'bucket': 'cx', 'points': 2}],
  'axis': 'law_chaos'},
 {'id': 11,
  'text': 'Do you insist on repayment when lending money to friends?',
  'options': [{'value': 1,
               'text': "Yes, and I write up a contract so there's no misunderstanding.",
               'bucket': 'lx',
               'points': 2},
              {'value': 2, 'text': 'Yes, but I try to be flexible about the exact terms.', 'bucket': 'lx', 'points': 1},
              {'value': 3, 'text': "No, although it's sure nice to be repaid.", 'bucket': 'nx', 'points': 1},
              {'value': 4, 'text': 'No, they just owe me a favor.', 'bucket': 'nx', 'points': 2}],
  'axis': 'law_chaos'},
 {'id': 12,
  'text': 'Are you still in touch with childhood friends?',
  'options': [{'value': 1, 'text': 'Yes, we correspond regularly.', 'bucket': 'nx', 'points': 2},
              {'value': 2, 'text': 'Yes, we try to keep in touch.', 'bucket': 'nx', 'points': 1},
              {'value': 3, 'text': 'No, I move around too much.', 'bucket': 'cx', 'points': 1},
              {'value': 4,
               'text': "No, I don't have anything in common with them anymore.",
               'bucket': 'cx',
               'points': 2}],
  'axis': 'law_chaos'},
 {'id': 13,
  'text': 'Do you donate time and money to improve the local community?',
  'options': [{'value': 1, 'text': 'Yes, the needs of the community are my top priority.', 'bucket': 'xg', 'points': 2},
              {'value': 2,
               'text': 'Yes, I donate as much as I can once my own needs are met.',
               'bucket': 'xg',
               'points': 1},
              {'value': 3, 'text': "No, I don't have enough time or money to spare.", 'bucket': 'xn', 'points': 1},
              {'value': 4,
               'text': 'No, my local community would be a waste of time and money.',
               'bucket': 'xn',
               'points': 2}],
  'axis': 'good_evil'},
 {'id': 14,
  'text': 'Your community is threatened with invasion.  Do you:',
  'options': [{'value': 1, 'text': 'Help defend it to your last breath?', 'bucket': 'xg', 'points': 2},
              {'value': 2, 'text': 'Defend the area with the rest of your community?', 'bucket': 'xg', 'points': 1},
              {'value': 3, 'text': 'Flee as soon as things look grim?', 'bucket': 'xe', 'points': 1},
              {'value': 4, 'text': 'Cut a deal with the enemy to act as a spy?', 'bucket': 'xe', 'points': 2}],
  'axis': 'good_evil'},
 {'id': 15,
  'text': 'If you were injured and required immediate assistance, would members of your home town agree to help?',
  'options': [{'value': 1, 'text': "Yes, because they know I'd do the same for them.", 'bucket': 'xn', 'points': 2},
              {'value': 2,
               'text': "Yes, because I'm generally well liked in my home town.",
               'bucket': 'xn',
               'points': 1},
              {'value': 3,
               'text': "Probably not, because I'm distrusted in my home town.",
               'bucket': 'xe',
               'points': 1},
              {'value': 4,
               'text': "Definitely not, I've made some enemies in my home town.",
               'bucket': 'xe',
               'points': 2}],
  'axis': 'good_evil'},
 {'id': 16,
  'text': 'Do you respect the laws and authorities of the community?',
  'options': [{'value': 1, 'text': 'Yes, without question.', 'bucket': 'lx', 'points': 2},
              {'value': 2, 'text': "Yes, they're generally the best way to govern.", 'bucket': 'lx', 'points': 1},
              {'value': 3,
               'text': "When it suits me--there are some laws I just don't agree with.",
               'bucket': 'cx',
               'points': 1},
              {'value': 4,
               'text': "I don't pay attention to the authorities; they've got no hold on me.",
               'bucket': 'cx',
               'points': 2}],
  'axis': 'law_chaos'},
 {'id': 17,
  'text': 'Do members of your home town shun, avoid, or mock you?',
  'options': [{'value': 1,
               'text': "Yes, their small minds can't handle anyone outside the norm.",
               'bucket': 'cx',
               'points': 2},
              {'value': 2, 'text': "Some do, because I don't always fit in.", 'bucket': 'cx', 'points': 1},
              {'value': 3, 'text': "No, I'm generally seen as normal.", 'bucket': 'nx', 'points': 1},
              {'value': 4,
               'text': 'No, I set the standard for what is normal in my community.',
               'bucket': 'nx',
               'points': 2}],
  'axis': 'law_chaos'},
 {'id': 18,
  'text': 'Would you stand for office or seek to represent the interests of the community in some public manner?',
  'options': [{'value': 1, 'text': "To do so would be an honor I'd joyously accept.", 'bucket': 'lx', 'points': 2},
              {'value': 2, 'text': "Of course.  It's everyone's duty to do so.", 'bucket': 'lx', 'points': 1},
              {'value': 3, 'text': 'Only if no one else could handle the job.', 'bucket': 'nx', 'points': 1},
              {'value': 4,
               'text': "No, I don't want to be responsible for the community's welfare.",
               'bucket': 'nx',
               'points': 2}],
  'axis': 'law_chaos'},
 {'id': 19,
  'text': 'Your country is wracked with famine.  Would you:',
  'options': [{'value': 1, 'text': 'Share what food you had with others?', 'bucket': 'xg', 'points': 2},
              {'value': 2,
               'text': 'Eat as little as possible yourself, and share the rest?',
               'bucket': 'xg',
               'points': 1},
              {'value': 3, 'text': 'Steal what food you needed to survive?', 'bucket': 'xe', 'points': 1},
              {'value': 4,
               'text': 'Steal as much food as possible, then sell it back to the community at a high price?',
               'bucket': 'xe',
               'points': 2}],
  'axis': 'good_evil'},
 {'id': 20,
  'text': "If offered enough money, would you slip a poison into your king's drink?",
  'options': [{'value': 1, 'text': "Yes, I've done similar things before.", 'bucket': 'xe', 'points': 2},
              {'value': 2, 'text': 'Yes, if I thought I could get away with it.', 'bucket': 'xe', 'points': 1},
              {'value': 3, 'text': 'No, although a vast sum of money would tempt me.', 'bucket': 'xn', 'points': 1},
              {'value': 4, 'text': "No, and I'd warn the king of the plot.", 'bucket': 'xn', 'points': 2}],
  'axis': 'good_evil'},
 {'id': 21,
  'text': 'A plague is sweeping across your country.  Would you:',
  'options': [{'value': 1, 'text': 'Undertake a dangerous mission to find the cure?', 'bucket': 'xg', 'points': 2},
              {'value': 2, 'text': 'Heal the sick as best you can?', 'bucket': 'xg', 'points': 1},
              {'value': 3, 'text': 'Avoid contact with the sick?', 'bucket': 'xn', 'points': 1},
              {'value': 4, 'text': 'Flee the country?', 'bucket': 'xn', 'points': 2}],
  'axis': 'good_evil'},
 {'id': 22,
  'text': 'Do you respect the lawful authority of the rulers of the land?',
  'options': [{'value': 1, 'text': 'Yes, Long live the queen!', 'bucket': 'lx', 'points': 2},
              {'value': 2, 'text': 'Yes, our rulers are generally fair and just.', 'bucket': 'lx', 'points': 1},
              {'value': 3, 'text': 'No, a ruler is no better than anyone else.', 'bucket': 'cx', 'points': 1},
              {'value': 4, 'text': 'No, rulers are invariably corrupted by power.', 'bucket': 'cx', 'points': 2}],
  'axis': 'law_chaos'},
 {'id': 23,
  'text': 'If you were offered a reasonably lucrative deal, would you spy for a hostile foreign power?',
  'options': [{'value': 1,
               'text': 'Yes, because this nation could stand to be knocked down a peg.',
               'bucket': 'cx',
               'points': 2},
              {'value': 2, 'text': "Yes, because the nation's secrets mean little to me.", 'bucket': 'cx', 'points': 1},
              {'value': 3, 'text': 'No, because I might get caught.', 'bucket': 'nx', 'points': 1},
              {'value': 4,
               'text': "No, because I'd never violate the trust my nation puts in me.",
               'bucket': 'nx',
               'points': 2}],
  'axis': 'law_chaos'},
 {'id': 24,
  'text': 'Do you rely on the government to enforce contracts and property rights?',
  'options': [{'value': 1,
               'text': 'Yes, because maintaining the rule of law is more important than any individual dispute.',
               'bucket': 'lx',
               'points': 2},
              {'value': 2,
               'text': 'Yes, because the courts are best equipped to handle such disputes.',
               'bucket': 'lx',
               'points': 1},
              {'value': 3,
               'text': "Are you kidding me?  The government can't even pave roads.",
               'bucket': 'nx',
               'points': 1},
              {'value': 4,
               'text': "Absolutely not.  If I can't defend it myself, I don't deserve to have it.",
               'bucket': 'nx',
               'points': 2}],
  'axis': 'law_chaos'},
 {'id': 25,
  'text': 'If imprisoned, would you injure or kill others to escape?',
  'options': [{'value': 1, 'text': "Yes.  Serves 'em right for locking me up.", 'bucket': 'xe', 'points': 2},
              {'value': 2, 'text': 'Yes.  They knew the risks when they took the job.', 'bucket': 'xe', 'points': 1},
              {'value': 3, 'text': 'No, except for minor wounds that will heal easily.', 'bucket': 'xn', 'points': 1},
              {'value': 4, 'text': 'No.  Those guards are just doing their jobs.', 'bucket': 'xn', 'points': 2}],
  'axis': 'good_evil'},
 {'id': 26,
  'text': "Do you accept a noble's right to treat badly the serfs who work on his land?",
  'options': [{'value': 1, 'text': "Yes. They're lucky they're not slaves.", 'bucket': 'xn', 'points': 2},
              {'value': 2, 'text': 'Yes, because sometimes only fear will motivate them.', 'bucket': 'xn', 'points': 1},
              {'value': 3, 'text': 'No, nobles should rule as kindly as possible.', 'bucket': 'xg', 'points': 1},
              {'value': 4,
               'text': 'No one has any "right" to treat another badly.  Period.',
               'bucket': 'xg',
               'points': 2}],
  'axis': 'good_evil'},
 {'id': 27,
  'text': 'You have accidentally committed a crime.  Do you:',
  'options': [{'value': 1,
               'text': 'Turn yourself in, and attempt to make restitution to the victim?',
               'bucket': 'xg',
               'points': 2},
              {'value': 2,
               'text': 'Turn yourself in, throwing yourself on the mercy of the court?',
               'bucket': 'xg',
               'points': 1},
              {'value': 3, 'text': 'Hide your involvement, lying if you have to?', 'bucket': 'xe', 'points': 1},
              {'value': 4, 'text': 'Try to pin the crime on another?', 'bucket': 'xe', 'points': 2}],
  'axis': 'good_evil'},
 {'id': 28,
  'text': 'If guilty, would you confess to a crime?',
  'options': [{'value': 1, 'text': 'Yes, because it is my duty to do so.', 'bucket': 'lx', 'points': 2},
              {'value': 2, 'text': 'Yes, because it might get me a lighter sentence.', 'bucket': 'lx', 'points': 1},
              {'value': 3, 'text': "No, I'd make the magistrates prove my guilt.", 'bucket': 'nx', 'points': 1},
              {'value': 4, 'text': 'No, and I\'d try to "prove" my own innocence.', 'bucket': 'nx', 'points': 2}],
  'axis': 'law_chaos'},
 {'id': 29,
  'text': 'Would you express a revolutionary political opinion if threatened with punishment?',
  'options': [{'value': 1, 'text': "Yes, I'd rather be punished than remain silent.", 'bucket': 'cx', 'points': 2},
              {'value': 2, 'text': "Yes.  Somebody's got to speak the truth.", 'bucket': 'cx', 'points': 1},
              {'value': 3,
               'text': 'No, although I might privately express my opinion to friends.',
               'bucket': 'nx',
               'points': 1},
              {'value': 4, 'text': "No, politics aren't worth getting worked up about.", 'bucket': 'nx', 'points': 2}],
  'axis': 'law_chaos'},
 {'id': 30,
  'text': 'While traveling, you witness an assault.  You are ordered to testify, which will delay your travel '
          'significantly.  Do you:',
  'options': [{'value': 1, 'text': 'Slip out of town at night to avoid testifying.', 'bucket': 'cx', 'points': 2},
              {'value': 2, 'text': 'Deny you saw anything.', 'bucket': 'cx', 'points': 1},
              {'value': 3, 'text': 'Remain reluctantly, testify, and leave.', 'bucket': 'lx', 'points': 1},
              {'value': 4,
               'text': "Remain until the trial's conclusion in case further testimony is needed.",
               'bucket': 'lx',
               'points': 2}],
  'axis': 'law_chaos'},
 {'id': 31,
  'text': 'What is the best use of wealth?',
  'options': [{'value': 1, 'text': 'To help the destitute and less fortunate.', 'bucket': 'xg', 'points': 2},
              {'value': 2, 'text': 'Provide for the needs of friends and family.', 'bucket': 'xg', 'points': 1},
              {'value': 3, 'text': 'To stay on top of the heap yourself.', 'bucket': 'xe', 'points': 1},
              {'value': 4,
               'text': 'To not only stay on top, but keep others from climbing to your level.',
               'bucket': 'xe',
               'points': 2}],
  'axis': 'good_evil'},
 {'id': 32,
  'text': 'When confronted by beggars, do you:',
  'options': [{'value': 1, 'text': 'Give generously?', 'bucket': 'xg', 'points': 2},
              {'value': 2, 'text': 'Give moderately?', 'bucket': 'xg', 'points': 1},
              {'value': 3,
               'text': "Give only what you wouldn't miss anyway--a dollar or two at the most?",
               'bucket': 'xn',
               'points': 1},
              {'value': 4, 'text': 'Ignore them as you walk by?', 'bucket': 'xn', 'points': 2}],
  'axis': 'good_evil'},
 {'id': 33,
  'text': 'By using magic, you could fool village merchants into thinking your copper pieces were made of gold. Do '
          'you?',
  'options': [{'value': 1, 'text': "Yes, and I'll buy as much as I can.", 'bucket': 'xe', 'points': 2},
              {'value': 2, 'text': "Yes, but I'll only cheat the rich merchants.", 'bucket': 'xe', 'points': 1},
              {'value': 3, 'text': "No, it's too risky.", 'bucket': 'xn', 'points': 1},
              {'value': 4, 'text': 'No, those merchants have families to feed.', 'bucket': 'xn', 'points': 2}],
  'axis': 'good_evil'},
 {'id': 34,
  'text': 'You have two job offers.  One pays more, but the other is secure and steady.  Which do you choose?',
  'options': [{'value': 1,
               'text': 'Definitely the lucrative job; steady work sounds like drudgery.',
               'bucket': 'nx',
               'points': 2},
              {'value': 2,
               'text': "Probably the lucrative job, although I'd look into the secure job.",
               'bucket': 'nx',
               'points': 1},
              {'value': 3,
               'text': 'The secure job, unless the other job was outrageously lucrative.',
               'bucket': 'lx',
               'points': 1},
              {'value': 4,
               'text': 'Definitely the secure job, because I plan for the long term.',
               'bucket': 'lx',
               'points': 2}],
  'axis': 'law_chaos'},
 {'id': 35,
  'text': "What's the best path to wealth?",
  'options': [{'value': 1,
               'text': "It's a matter of luck and being in the right place at the right time.",
               'bucket': 'cx',
               'points': 2},
              {'value': 2,
               'text': 'Staying flexible so you can take advantage of good opportunities.',
               'bucket': 'cx',
               'points': 1},
              {'value': 3,
               'text': 'Following a long-term plan that incorporates a comfortable level of risk.',
               'bucket': 'lx',
               'points': 1},
              {'value': 4, 'text': 'Hard work and perseverance.', 'bucket': 'lx', 'points': 2}],
  'axis': 'law_chaos'},
 {'id': 36,
  'text': 'If you accepted a job or contract, would you try to finish the task even if it got much more dangerous?',
  'options': [{'value': 1, 'text': 'Yes, my word is my bond.', 'bucket': 'nx', 'points': 2},
              {'value': 2,
               'text': "Yes, because it's good to have a reputation for dependability.",
               'bucket': 'nx',
               'points': 1},
              {'value': 3, 'text': "You can bet I'd be renegotiating.", 'bucket': 'cx', 'points': 1},
              {'value': 4,
               'text': "If it's no longer a good deal, then the deal is off.",
               'bucket': 'cx',
               'points': 2}],
  'axis': 'law_chaos'}]

def get_questions(mode):
    if mode == "full":
        return FULL_QUESTIONS
    raise ValueError("invalid mode")


def mode_question_total(mode: str) -> int:
    try:
        return MODE_QUESTION_TOTAL[mode]
    except KeyError as exc:
        raise ValueError("invalid mode") from exc
